pipeline {
    agent none
    environment {
        PUBLIC_URL       = 'https://aldybw.github.io/simple-python-pyinstaller-app'
        GITHUB_TOKEN     = credentials('jenkins-github-token')
        GITHUB_REPOSITORY = 'aldybw/simple-python-pyinstaller-app'
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux:python2'
                }
            }
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
                sh 'chmod +x ./jenkins/scripts/github-pages.sh && ./jenkins/scripts/github-pages.sh'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}


// node {
//     stage('Build') {
//         docker.image('python:2-alpine').inside {
//             checkout scm
//             sh 'python -m py_compile sources/add2vals.py sources/calc.py'
//         }
//     }

//     stage('Test') {
//         try {
//             docker.image('qnib/pytest').inside {
//                 checkout scm
//                 sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
//             }
//         } finally {
//             junit 'test-reports/results.xml'
//         }
//     }

//     stage('Deliver') {
//         try {
//             docker.image('cdrx/pyinstaller-linux:python2').inside {
//                 checkout scm
//                 sh 'pyinstaller --onefile sources/add2vals.py'
//             }
//         } finally {
//             archiveArtifacts 'dist/add2vals'
//         }
//     }
// }